obsFile:          data/spatiotemporal/obs.tsv;
# tempSampFile:    data/spatiotemporal/currycarbon_result.tsv;
spatGridFile:     data/spatiotemporal/spatial_grid.tsv;
tempGrid:         absolute(years = c(-7000, -6000, -5000, -4000));
searchDepVarsPos: c(depC1 = 0.0461299, depC2 = 0.00014293);
#searchObsFile:         data/spatiotemporal/obs.tsv;
kerndef:          c(
                     depC1 = k(SqEx, c(space = 800, time = 800)), #c(space = 800, time = 800)),
                     depC2 = k(SqEx, c(space = 800, time = 800))
                  );
outMode: Normal;  # Obs(3);
outFile:          data/spatiotemporal/basic_result.tsv;
indepMaxFilter:   c(space = 2000, time = 2000);
normalisation:    NormBySpace;
