obsFile:          data/spatiotemporal/obs.tsv;
tempSampFile:     data/spatiotemporal/currycarbon_result.tsv;
marginaliseOverTempSamp: true;
gridFile:     data/spatiotemporal/grid.tsv;
tempGrid:         absolute(years = c(-7000, -6000, -5000));
#tempGrid:         absolute(years = c(-5000));
#tempGrid:        relative(years = c(100, -100, -200));
#searchDepVarsPos: c(depC1 = 0.0461299, depC2 = 0.00014293);
searchObsFile:    data/spatiotemporal/search_obs.tsv;
algodef:          def(
                    algorithm = GPR,
                    depVars = c(
                       depC1 = k(SqEx, c(space = 800, time = 700), nugget = 0.5),
                       depC2 = k(SqEx, c(space = 900, time = 800), nugget = 0.5)
                    )
                  );
# read dists from .tsv
#obsGridDistFile:  data/spatiotemporal/obsGridDistFile.tsv;
#obsObsDistFile:   data/spatiotemporal/obsObsDistFile.tsv;
#gridGridDistFile: data/spatiotemporal/gridGridDistFile.tsv;
# read dists from .cbor
#obsGridDistFile:  data/spatiotemporal/obsGridDistFile.cbor;
#obsObsDistFile:   data/spatiotemporal/obsObsDistFile.cbor;
#gridGridDistFile: data/spatiotemporal/gridGridDistFile.cbor;
outFile:          data/spatiotemporal/basic_result.tsv;
