obsFile:         data/spatiotemporal/obs.tsv;
# tempSampFile:    data/spatiotemporal/currycarbon_result.tsv;
spatGridFile:    data/spatiotemporal/spatial_grid.tsv;
tempGrid:        c(-7000, -6000, -5000);
depVars:         c(depC1 = 0.0461299, depC2 = 0.00014293);
kerndef:         c(
                    depC1 = k(SqEx, 0.1, c(space = 800, time = 800)),
                    depC2 = k(SqEx, 0.1, c(space = 800, time = 800))
                 );
outFile:         data/spatiotemporal/basic_result.tsv;
spaceTimeFilter: filter(2000,2000);
threads:         Detect;
normalization:   NormBySpace;
