obsFile:         data/spatiotemporal/obs.tsv;
kerndef:         c(
                    depC1 = k(SqEx, c(space = 200:1000:200, time = 200:1000:200)),
                    depC2 = k(SqEx, c(space = 200:1000:200, time = 200:1000:200))
                 );
testFraction:    0.2;
iterations:      3;
outFile:         data/spatiotemporal/cross.tsv;
outMode:         Summed;
