obsFile:         data/spatiotemporal/obs.tsv;
kerndef:         c(
                    depC1 = k(SqEx, 0.1, c(space = 700:900:100, time = 700:900:100)),
                    depC2 = k(SqEx, 0.1, c(space = 700:900:100, time = 800))
                 );
testFraction:    0.2;
iterations:      2;
outFile:         data/spatiotemporal/cross.tsv;
threads:         Detect;
