obsFile:      data/spatiotemporal/obs.tsv;
algodef:      def(
              algorithm = GPR,
                depVars = c(
                  depC1 = k(SqEx, c(space = 200:1200:200, time = 200:1200:200), nugget = 0.001),
                  depC2 = k(SqEx, c(space = 200:1200:200, time = 200:1200:200), nugget = 0.001)
                )
              );
testFraction: 0.2;
iterations:   3;
outFile:      data/spatiotemporal/cross.tsv;
