obsFile:         test2Obs.tsv
#tempSampFile:    test2CurrycarbonSamples.tsv
spatGridFile:    test2Grid.tsv
tempGrid:        c(-7000, -6000, -5000)
depVars:         c(depC1 = 0.0461299, depC2 = 0.00014293)
algorithm:       kas(shapes = c(depC1 = normal(200, 200), depC2 = normal(200, 200)))
#algorithm:       kas(c(varC1 = uniform(300, 300), varC2 = uniform(300, 300)))
outFile:         test_res/test2Search.tsv
spaceTimeFilter: filter(2000,2000)
threads:         Detect
normalization:   NormBySpace