obsFile:      test2Obs.tsv
spatGridFile: test2Grid.tsv
tempGrid:     c(-7000, -6000, -5000)
depVars:      c(varC1 = 0.0461299, varC2 = 0.00014293)
#algorithm:   SepIDW(c(varC1 = LinearSum(0.00001, 0.00001), varC2 = LinearSum(0.00001, 0.00001)), Maximum)
algorithm:    KernSmooth(c(varC1 = Normal(200, 200), varC2 = Normal(200, 200)))
outFile:      test_res/test2Search.tsv