obsFile:         test2Obs.tsv
spatGridFile:    test2Grid.tsv
tempGrid:        c(-7000, -6000, -5000)
depVars:         c(varC1 = 0.0461299, varC2 = 0.00014293)
#algorithm:       IDW(c(varC1 = Kernel(0.0005, 0.0005, 0.03), varC2 = Kernel(0.0005, 0.0005, 0.03)))
algorithm:       KAS(c(varC1 = Kernel(0.001, 0.001, 0.03), varC2 = Kernel(0.001, 0.001, 0.03)))
outFile:         test_res/test2Search.tsv
#spaceTimeFilter: SpaceTimeFilter(2000,2000)
threads:         Detect
normalization:   NormBySpace